env:
  browser: true
  es6: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  chrome: writable
  easyPeasyAuth: writable
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  max-len: ["error", { "code": 120 }]
  no-bitwise: "off"
  no-alert: "off"
